kind: "Service"
apiVersion: "v1"
metadata:
  name: "falkonry-data-services"
  labels:
    function: "data-services"
    party: "falkonry"
spec:
  ports:
    - name: data-services
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: data-services-http
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: data-services-ws
      port: 8444
      targetPort: 8444
      protocol: TCP
  selector:
    name: "falkonry-data-services"